[package]
name = "tugger"
version = "0.3.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Package and distribute applications"
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"
build = "build.rs"

[dependencies]
anyhow = "1.0"
codemap = "0.1"
codemap-diagnostic = "0.1"
duct = "0.13"
handlebars = "3.0"
glob = "0.3"
hex = "0.4"
lazy_static = "1.4"
reqwest = { version = "0.10", features = ["blocking"] }
sha2 = "0.9"
slog = "2.4"
starlark = "0.3.1"
tar = "0.4"
url = "2.1"
uuid = { version = "0.8", features = ["v4", "v5"] }
walkdir = "2"
xml-rs = "0.8"
zip = "0.5"

[dependencies.starlark-dialect-build-targets]
version = "0.2.0-pre"
path = "../starlark-dialect-build-targets"

[dev-dependencies]
msi = "0.2"
tempdir = "0.3"
